/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rekomendasi_kuliner;

//import java.beans.Statement;
//import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import com.mysql.jdbc.Statement;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.util.Arrays;

/**
 *
 * @author user
 */
public class Aplikasi extends javax.swing.JFrame {

    /**
     * Creates new form Aplikasi
     */
    public Aplikasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbHarga = new javax.swing.JComboBox();
        cbFasilitas = new javax.swing.JComboBox();
        tombolRekomendasi = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cbJarak = new javax.swing.JComboBox();
        pbRank1 = new javax.swing.JProgressBar();
        pbRank2 = new javax.swing.JProgressBar();
        pbRank3 = new javax.swing.JProgressBar();
        pbRank4 = new javax.swing.JProgressBar();
        tfRank1 = new javax.swing.JTextField();
        tfRank2 = new javax.swing.JTextField();
        tfRank3 = new javax.swing.JTextField();
        tfRank4 = new javax.swing.JTextField();
        cbSuasana = new javax.swing.JComboBox<String>();
        pbRank5 = new javax.swing.JProgressBar();
        pbRank6 = new javax.swing.JProgressBar();
        pbRank7 = new javax.swing.JProgressBar();
        tfRank5 = new javax.swing.JTextField();
        tfRank6 = new javax.swing.JTextField();
        tfRank7 = new javax.swing.JTextField();
        pbRank8 = new javax.swing.JProgressBar();
        tfRank8 = new javax.swing.JTextField();
        tombolReset = new javax.swing.JButton();
        tfRank9 = new javax.swing.JTextField();
        pbRank9 = new javax.swing.JProgressBar();
        tfRank10 = new javax.swing.JTextField();
        pbRank10 = new javax.swing.JProgressBar();

        jLabel6.setText("jLabel6");

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPK Rekomendasi Kuliner Kelompok 3");

        jLabel3.setText("Harga");

        jLabel4.setText("Fasilitas");

        jLabel5.setText("Jarak");

        cbHarga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<10.000", "10.000-20.000", "20.000-30.000", "30.000-40.000", ">40.000" }));
        cbHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHargaActionPerformed(evt);
            }
        });

        cbFasilitas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<2", "2-4", "5-7", "8-10", ">10" }));

        tombolRekomendasi.setText("Rekomendasi");
        tombolRekomendasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolRekomendasiActionPerformed(evt);
            }
        });

        jLabel15.setText("Suasana");

        cbJarak.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<1", "1-2", "2-3", "3-4", ">5" }));

        tfRank1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRank1ActionPerformed(evt);
            }
        });

        cbSuasana.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sangat Nyaman", "Sedang", "Tidak Nyaman" }));

        tombolReset.setText("Reset");
        tombolReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfRank4, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pbRank4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfRank2)
                        .addGap(18, 18, 18)
                        .addComponent(pbRank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfRank3)
                        .addGap(18, 18, 18)
                        .addComponent(pbRank3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfRank6)
                        .addGap(18, 18, 18)
                        .addComponent(pbRank6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfRank8)
                        .addGap(18, 18, 18)
                        .addComponent(pbRank8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfRank5, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pbRank5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfRank7)
                        .addGap(18, 18, 18)
                        .addComponent(pbRank7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfRank1)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbHarga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbFasilitas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbJarak, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSuasana, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tombolRekomendasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombolReset)
                            .addComponent(pbRank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfRank9)
                        .addGap(18, 18, 18)
                        .addComponent(pbRank9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfRank10)
                        .addGap(18, 18, 18)
                        .addComponent(pbRank10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbJarak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbSuasana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolRekomendasi)
                    .addComponent(tombolReset))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbRank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbRank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbRank3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRank3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbRank4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRank4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfRank5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbRank6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRank6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pbRank5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfRank7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbRank8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRank8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pbRank7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbRank9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRank9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbRank10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRank10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection con;

    //method koneksidatabase
    public void koneksiDatabase() {
        String driver = "com.mysql.jdbc.Driver";//nama driver
        String url = "jdbc:mysql://localhost/data_kuliner";//nama database
        String usr = "root";//nama user database
        String pwd = "";//password database
        try {
            Class.forName(driver);
            con = (Connection) DriverManager.getConnection(url, usr, pwd);
            //JOptionPane.showMessageDialog(rootPane, "Koneksi Berhasil...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal Koneksi..");
        }
    }
    
    //variable-variable data
    public static String nama[] = new String[50];
    public static int harga[] = new int[50];
    public static int fasilitas[] = new int[50];
    public static int jarak[] = new int[50];
    public static int suasana[] = new int[50];
    public static int nData = 50;
    double panjangString = 4;
    public void ambilDataKuliner(){
        try{
            koneksiDatabase();
            String sql = "SELECT * FROM bobot_alternatif";
            Statement stat = (Statement) con.createStatement();
            ResultSet res = stat.executeQuery(sql);
            int i=0;
            while (res.next()) {
                //Untuk menyimpan Data dari dalam Table di database ke dalam array
                nama[i] = res.getString("nama");
                harga[i] = Integer.parseInt(res.getString("harga"));
                fasilitas[i] = Integer.parseInt(res.getString("fasilitas"));
                jarak[i] = Integer.parseInt(res.getString("jarak"));
                suasana[i] = Integer.parseInt(res.getString("suasana"));
                i++;
            }
            System.out.println("=====Data Kuliner =====");
            
            for(int j=0; j<nData;j++){
                
                //System.out.print(" "+nama[j]);
                System.out.print(" "+harga[j]);
                System.out.print(" "+fasilitas[j]);
                System.out.print(" "+jarak[j]);
                System.out.print(" "+suasana[j]);
                System.out.println("");
            }
            System.out.println("");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan" + e);
        }
    }
    ALgen a = new ALgen();
    double [][] individu = new double[nData][4];
    double v[][] = new double[50][4];
    double w[] = {0.4, 0.2, 0.25, 0.15};
    public double r[][] = new double[50][4];
    SkorParameter skor = new SkorParameter();
    public double v_tot[] = new double[50];
    DataKuliner dk[] = new DataKuliner[50];
    public double [][] saw(double hasil[][]){
        ambilDataKuliner();
        //memberikan skor tiap alternatif
        System.out.println("====Memberi skor nilai alternative====");
        for (int i = 0; i < nData; i++) {
            //skor harga
            v[i][0] = skor.getSkorHarga(harga[i], hargaP);
            System.out.print(v[i][0]+"\t");
            //skor fasilitas
            v[i][1] = skor.getSkorFasilitas(fasilitas[i], fasilitasP);
            System.out.print(v[i][1]+"\t");
            //skor jarak
            v[i][2] = skor.getSkorJarak(jarak[i], jarakP);
            System.out.print(v[i][2]+"\t");
            //skor suasana
            v[i][3] = skor.getSkorSuasana(suasana[i], suasanaP);
            System.out.println(v[i][3]);
        }
        
        double max[] = new double[4];
        double min[] = new double[4];
        
        //mencari nilai maximum kolom fasilitas dan suasana, minimum kolom harga dan jarak
        for (int j = 0; j < 4; j++) {
            if(j == 0 || j == 2){
                min[j] = v[0][j];
                for (int i = 0; i < nData; i++) {
                    if(min[j] >= v[i][j]){
                        min[j] = v[i][j];
                    }
                }
                System.out.println(j+":"+min[j]);
            }
            else if(j == 1 || j == 3){
                max[j]=v[0][j];
                for (int i = 0; i < nData; i++) {
                    if(max[j] <= v[i][j]){
                        max[j] = v[i][j];
                    }
                }
                System.out.println(j+":"+max[j]);
            }
        }
        
        //mencari nilai ternormalisasi
        System.out.println("====Hasil Normalisasi Data Kuliner====");
        for (int i = 0; i < nData; i++) {
            for (int j = 0; j < 4; j++) {
                if(j == 1 || j == 3){
                    r[i][j] = v[i][j]/max[j];
                    System.out.print(String.format("%.4f", r[i][j])+"\t");
                    
                }
                else if (j == 0 || j == 2){
                    r[i][j] = min[j]/v[i][j];
                    System.out.print(String.format("%.4f", r[i][j])+"\t");
                    
                }
            }
            System.out.println("");
        }
        
        //perhitungan v total
//        System.out.println("====Perhitungan v ====");
//        for (int i = 0; i < nData; i++) {
//            for (int j = 0; j < 4; j++) {
//                v_tot[i] += w[j]*r[i][j];
//            }
//            System.out.println(String.format("%.4f",v_tot[i]));
//            dk[i] = new DataKuliner(nama[i], harga[i], fasilitas[i], jarak[i], suasana[i], v_tot[i]);
//        }
        return r;
//        Arrays.sort(dk);
//        
//        tfRank1.setText(dk[0].getNama());
//        tfRank2.setText(dk[1].getNama());
//        tfRank3.setText(dk[2].getNama());
//        tfRank4.setText(dk[3].getNama());
//        tfRank5.setText(dk[4].getNama());
//        tfRank6.setText(dk[5].getNama());
//        tfRank7.setText(dk[6].getNama());
//        tfRank8.setText(dk[7].getNama());
//        tfRank9.setText(dk[8].getNama());
//        tfRank10.setText(dk[9].getNama());
//        
//        pbRank1.setValue((int)(dk[0].getV_tot()*100));
//        pbRank2.setValue((int)(dk[1].getV_tot()*100));
//        pbRank3.setValue((int)(dk[2].getV_tot()*100));
//        pbRank4.setValue((int)(dk[3].getV_tot()*100));
//        pbRank5.setValue((int)(dk[4].getV_tot()*100));
//        pbRank6.setValue((int)(dk[5].getV_tot()*100));
//        pbRank7.setValue((int)(dk[6].getV_tot()*100));
//        pbRank8.setValue((int)(dk[7].getV_tot()*100));
//        pbRank9.setValue((int)(dk[8].getV_tot()*100));
//        pbRank10.setValue((int)(dk[9].getV_tot()*100));
    }
    
    int hargaP, fasilitasP, jarakP, suasanaP;
    private void tombolRekomendasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolRekomendasiActionPerformed
        //harga
        if(cbHarga.getSelectedIndex() == 0){
            hargaP = 2;
        } else if(cbHarga.getSelectedIndex() == 1){
            hargaP = 4;
        } else if(cbHarga.getSelectedIndex() == 2){
            hargaP = 6;
        } else if(cbHarga.getSelectedIndex() == 3){
            hargaP = 8;
        } else if(cbHarga.getSelectedIndex() == 4){
            hargaP = 10;
        }
        
        //fasilitas
        if(cbFasilitas.getSelectedIndex() == 0){
            fasilitasP = 2;
        } else if(cbFasilitas.getSelectedIndex() == 1){
            fasilitasP = 4;
        } else if(cbFasilitas.getSelectedIndex() == 2){
            fasilitasP = 6;
        } else if(cbFasilitas.getSelectedIndex() == 3){
            fasilitasP = 8;
        } else if(cbFasilitas.getSelectedIndex() == 4){
            fasilitasP = 10;
        }
        
        //jarak
        if(cbJarak.getSelectedIndex() == 0){
            jarakP = 2;
        } else if(cbJarak.getSelectedIndex() == 1){
            jarakP = 4;
        } else if(cbJarak.getSelectedIndex() == 2){
            jarakP = 6;
        } else if(cbJarak.getSelectedIndex() == 3){
            jarakP = 8;
        } else if(cbJarak.getSelectedIndex() == 4){
            jarakP = 10;
        }
        
        //suasana
        if(cbSuasana.getSelectedIndex() == 0){
            suasanaP = 10;
        } else if(cbSuasana.getSelectedIndex() == 1){
            suasanaP = 7;
        } else if(cbSuasana.getSelectedIndex() == 2){
            suasanaP = 3;
        }
        
        tombolRekomendasi.setEnabled(false);
    }//GEN-LAST:event_tombolRekomendasiActionPerformed

    private void tombolResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolResetActionPerformed
        this.dispose();
        String args[] = new String[1];
        Aplikasi a = new Aplikasi();
        a.main(args);
    }//GEN-LAST:event_tombolResetActionPerformed

    private void tfRank1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRank1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRank1ActionPerformed

    private void cbHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikasi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbFasilitas;
    private javax.swing.JComboBox cbHarga;
    private javax.swing.JComboBox cbJarak;
    private javax.swing.JComboBox<String> cbSuasana;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar pbRank1;
    private javax.swing.JProgressBar pbRank10;
    private javax.swing.JProgressBar pbRank2;
    private javax.swing.JProgressBar pbRank3;
    private javax.swing.JProgressBar pbRank4;
    private javax.swing.JProgressBar pbRank5;
    private javax.swing.JProgressBar pbRank6;
    private javax.swing.JProgressBar pbRank7;
    private javax.swing.JProgressBar pbRank8;
    private javax.swing.JProgressBar pbRank9;
    private javax.swing.JTextField tfRank1;
    private javax.swing.JTextField tfRank10;
    private javax.swing.JTextField tfRank2;
    private javax.swing.JTextField tfRank3;
    private javax.swing.JTextField tfRank4;
    private javax.swing.JTextField tfRank5;
    private javax.swing.JTextField tfRank6;
    private javax.swing.JTextField tfRank7;
    private javax.swing.JTextField tfRank8;
    private javax.swing.JTextField tfRank9;
    private javax.swing.JButton tombolRekomendasi;
    private javax.swing.JButton tombolReset;
    // End of variables declaration//GEN-END:variables
}
